NS.FRN.Web/Controllers/FurnitureController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using NS.FRN.Web.Models;
using NS.FRN.Business;
using NS.FRN.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using NS.FRN.Data.Entities;
using Microsoft.AspNetCore.Authorization;

namespace NS.FRN.Web.Controllers;


public class FurnitureController : Controller
{
    private readonly ILogger<FurnitureController> _logger;
    private readonly IFurnitureBusiness _iFurnitureBusiness;


    public FurnitureController(ILogger<FurnitureController> logger, IFurnitureBusiness iFurnitureBusiness)
    {
        _logger = logger;
        _iFurnitureBusiness = iFurnitureBusiness;
    }

    // public IActionResult AddtoCart(int id){
    //    using(var context=new FRNDBContext()){
    //     var query=context.Products.Where(x=>x.ProductId==id).SingleOrDefault();
    //     return View(query);
    //    }
    // }

public IActionResult Index()
    {
        var productList = _iFurnitureBusiness.GetProductList();
        // var productList=context.Products.ToList();
        return View(productList);

    }
    public IActionResult ActivateDeactivateRecord(int Id)
    {
        _iFurnitureBusiness.ActivateDeactivateRecord(Id);
        return RedirectToAction(actionName: "ViewProductList", controllerName: "Home");
    }
 
    [HttpGet]
    public IActionResult Editview(int id)
    {
        using (var context = new FRNDBContext())
        {
            var data = context.Products.FirstOrDefault(x => x.Id == id);
            if (data != null)
            {
                var viewmodel = new Product()
                {
                    Id = data.Id,
                    Category = data.Category,
                    Price = data.Price,
                    Description = data.Description,
                    Name = data.Name,
                    // IsEligibleForDiscount = data.IsEligibleForDiscount,
                    Photo = data.Photo,
                    // IsActive = data.IsActive,
                    // IsDeleted = data.IsDeleted,
                    // CreatedOn = data.CreatedOn,
                    // CreatedBy = data.CreatedBy,
                    // ModifiedBy = data.ModifiedBy
                    // ModifiedOn = data.ModifiedOn

                };
                return View(viewmodel);
            }
            return RedirectToAction(actionName: "RoomDetail", controllerName: "Room");
        }
    }
    
    [HttpPost]
    public IActionResult Editview(Product model)
    {
        using (var context = new FRNDBContext())
        {
            var data = context.Products.Find(model.Id);
            if (data != null)
            {
                data.Id = model.Id;
                data.Name = model.Name;
                data.Category = model.Category;
                data.Price = model.Price;
                data.Photo = model.Photo;
                data.Description = model.Description;
                // data.IsEligibleForDiscount = model.IsEligibleForDiscount;
                context.SaveChanges();
                return RedirectToAction(actionName: "RoomDetail", controllerName: "Room");
            }
            return RedirectToAction(actionName: "RoomDetail", controllerName: "Room");
        }
    }
    [Authorize(Roles="2")]
       
    [HttpGet]
    public IActionResult AddToCart(int id)
    {
        var userId = HttpContext.User.Claims.FirstOrDefault(x => x.Type == "UserId")?.Value;
        CartViewModel cartViewModel = new CartViewModel();
        cartViewModel.ProductId = id;
        cartViewModel.UserId = Convert.ToInt64(userId);
        _iFurnitureBusiness.AddToCart(cartViewModel);
        return RedirectToAction("ViewCart");
    }
    [Authorize(Roles="2")]
    public IActionResult ViewCart()
    {
        long userId = Convert.ToInt64(HttpContext.User.Claims.FirstOrDefault(x => x.Type == "UserId")?.Value);
        var cartItems = _iFurnitureBusiness.GetCartItems(userId);
        return View(cartItems);
    }
    [Authorize(Roles="2")]
     public IActionResult MyOrders()
     
    { 
        long userId = Convert.ToInt64(HttpContext.User.Claims.FirstOrDefault(x => x.Type == "UserId")?.Value);
          var myOrders = _iFurnitureBusiness.GetMyOrders(userId);
        return View(myOrders);

    }
   
    [HttpPost]
     public IActionResult BuyNow(List<Cart> cart)
    {
        long userId = Convert.ToInt64(HttpContext.User.Claims.FirstOrDefault(x => x.Type == "UserId")?.Value);
        _iFurnitureBusiness.BuyNow(cart, (int)userId);
       return RedirectToAction ("ViewCart");
    }
    
    // // private class FRNDBContext : IDisposable
    // {
    //     internal readonly IEnumerable<object> Products;
    // }
}

NS.FRN.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NS.FRN.Web</title><link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NS.FRN.Web.styles.css" asp-append-version="true" />
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NS.FRN.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="UserDetails">Users</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AddFurniture">Add Furniture</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ViewProductList">View Furniture</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Furniture" asp-action="MyOrders">My Orders</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="LogOut">LogOut</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - NS.FRN.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
   
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

NS.FRN.Web/Views/Shared/_Layout3.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NS.FRN.Web</title><link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NS.FRN.Web.styles.css" asp-append-version="true" />
     <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Furniture Accessories Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @* <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="User">Users</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="AddFurniture">AddFurniture</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="ViewProductList">AddFurniture</a>
                        </li>
                    </ul>
                </div> *@
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    @* <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Furniture Accessories Management - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    *@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>